### ISSUE TITLE
Square image uploading in wrong orientation

### ISSUE THREAD

**Issue by AkimboDadz** [Black-Kro/Codebyte-Issues#4]
[See linked screenshot](https://imgur.com/a/U1Vr60O) for example. Original image was in proper orientation. Posted via Safari on iPhone XS Max running iOS 13.6.1

**Comment by bizzycola** [comment]
When clicking the image and viewing it, it appears in the correct orientation(on PC, using chrome).

**Comment by bizzycola** [comment]
![image](https://user-images.githubusercontent.com/845115/92388744-21d2c300-f15b-11ea-85a6-1c80cfc4de8d.png)
![image](https://user-images.githubusercontent.com/845115/92389161-ee446880-f15b-11ea-9c12-8e01d3b7c4a2.png)

**Comment by wheatjs** [comment]
Yeah I don't know if I can fix this on the front-end, I think this will have to be fixed on the media server

**Comment by bizzycola** [comment]
Fixed
