### ISSUE TITLE
Error loading users in /people

### ISSUE THREAD

**Issue by mcba1n** [Black-Kro/Codebyte-Issues#7]
It shows "load more". When you try to load more, it gives a "slow down" notification.

<img width="1680" alt="Screen Shot 2020-09-10 at 9 14 37 pm" src="https://user-images.githubusercontent.com/9088916/92722630-373e2c00-f3ab-11ea-9c04-73bd8eea02a9.png">

**Comment by bizzycola** [comment]
So you were like spam clicking a button? The load more button shows even if there aren't any more users to load, clicking it will still make the request every time so if you click it a lot fairly quickly it will rate limit you.

That being said, next API update should increase some of the rate limits and hopefully solve some issue(which with likely be soon)

**Comment by wheatjs** [comment]
Fixed
